- hosts: iview-ts
  vars:
    workdir: /opt/iview-admin/www

  tasks:
    - name: ensure iview-admin webui directory
      file: path={{ workdir }} state=directory mode=755

    - name: sync dist file
      synchronize: src=../dist/ dest={{ workdir }}/
